---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: Get hostname
      shell: echo $HOSTNAME
      register: result

    - name: Print the var
      debug:
        var: result.stdout
