---

- name: Network Getting Started First Playbook
  gather_facts: false
  hosts: unraid

  tasks:

    - name: Get hostname
      shell: echo $HOSTNAME
      register: result

    - name: Print the var
      debug:
        var: result.stdout
