---

- name: Network Getting Started First Playbook
  connection: ssh
  gather_facts: false
  hosts: all

  tasks:

    - name: Get hostname
      shell: echo $HOSTNAME
      register: result

    - name: Print the var
      debug:
        var: result.stdout
