---

- name: Lidarr Empty Freyr Cache
  gather_facts: false
  hosts: unraid

  tasks:
    # FACTS ##################################################################                                                                                                             #####
    - name: Lidarr Empty Freyr Cache
      community.docker.docker_container_exec:
        container: lidarr
        command: /bin/bash -c "rm /root/.cache/FreyrCLI/*"
        chdir: /root
      register: result

    - name: Print stdout
      ansible.builtin.debug:
        var: result.stdout