---

- name: Test task
  gather_facts: false
  hosts: all
  vars:
    target_dir: "/mnt/user/downloads/tv"

  tasks:
    # FACTS ##################################################################                                                                                                             #####
    - name: Ensure requirements in place
      package:
        name:
          - guestfs-tools
          - python3-libvirt
        state: present

    - name: Get VMs list
      community.libvirt.virt:
        command: list_vms
      register: existing_vms
      changed_when: no