---

- name: Test task
  gather_facts: false
  hosts: unraid

  tasks:
  - name: Get count of 'beers' nodes
    community.general.xml:
      path: /mnt/user/appdata/radarr/config.xml
      xpath: /Config/ApiKey
      count: true
    register: ApiKey
... 