---

- name: Test task
  gather_facts: false
  hosts: all

  tasks:
  - name: Check if WebUIRootFolder is already defined
    ansible.builtin.lineinfile:
      path: '/mnt/user/appdata/qbittorrent/qBittorrent/qBittorrent.conf'
      regexp: '^WebUI\RootFolder=/config/VueTorrent'
    changed_when: false
... 