---

- name: Test task
  gather_facts: false
  hosts: all
  vars:
    container_name: "sonarr"

  tasks:
    # FACTS ##################################################################                                                                                                             #####
    - name: Update Extended Scripts
      shell: |
        curl  https://raw.githubusercontent.com/RandomNinjaAtk/arr-scripts/main/{{ container_name }}/extended.conf --output  /mnt/user/appdata/extended.conf
    
