---

- name: Test task
  gather_facts: false
  hosts: all

  tasks:
    # FACTS ##################################################################                                                                                                             #####
    - name: Disk usage from command module
      command: df -h
      register: space
    - debug:
            var: space.stdout_lines

    - name: Send notify to Telegram
      community.general.telegram:
        token: '5270927352:AAHHbj1KefSx7XYffQke_NQGRxoo_L9q7YQ'
        api_args:
          chat_id: 5073078093
          parse_mode: "html"
          text: "{{ space.stdout_lines }}"
          disable_web_page_preview: true
          disable_notification: false