---

- name: Test task
  gather_facts: false
  hosts: unraid

  tasks:
  - name: Install requirements
    shell: |
      pip3 install lxml

# How to read an attribute value and access it in Ansible
  - name: Read an element's attribute values
    community.general.xml:
      path: /mnt/user/appdata/radarr/config.xml
      xpath: /Config/ApiKey
      content: attribute
    register: xmlresp

  - name: Show an attribute value
    ansible.builtin.debug:
      var: xmlresp.matches[0].validxhtml.validatedon
  
  - name: Print return information from the previous task
    ansible.builtin.debug:
      msg: "{{xmlresp.matches[0].validxhtml.validatedon }}"

  - name: Send notify to Telegram
    community.general.telegram:
      token: '5270927352:AAHHbj1KefSx7XYffQke_NQGRxoo_L9q7YQ'
      api_args:
        chat_id: 5073078093
        parse_mode: "html"
        text: "{{ ApiKey.stdout }}"
        disable_web_page_preview: true
        disable_notification: false  
... 

