---

- name: Test task
  gather_facts: false
  hosts: all
  vars:
    path: /mnt/user/appdata/qbittorrent/VueTorrent/

  tasks:
  - name: Task name
    stat:
      path: '{{ path }}'
    register: register_name

  - name: Clone a github repository
    git:
      repo: https://github.com/WDaan/VueTorrent.git
      dest: /mnt/user/appdata/qbittorrent/
      clone: yes
      update: yes
    when: not register_name.stat.exists

  - name: Check if WebUI\RootFolder is already defined
    lineinfile:
      state: absent
      path: /mnt/user/appdata/qbittorrent/qBittorrent/qBittorrent.conf
      regexp: WebUI\RootFolder=/config/VueTorrent
    check_mode: true
    changed_when: false # This just makes things look prettier in the logs
    register: check

  - name: Set WebUI\RootFolder in qBittorrent.conf
    ansible.builtin.lineinfile:
      path: /mnt/user/appdata/qbittorrent/qBittorrent/qBittorrent.conf
      regexp: '^WebUI\RootFolder=""'
      line: WebUI\RootFolder=/config/VueTorrent
    when: check.found == 0   
...