---

- name: Test task
  gather_facts: false
  hosts: all
  vars:
    target_dir: "/mnt/user/downloads/tv"

  tasks:
    # FACTS ##################################################################                                                                                                             #####
    - name: Check sufficient free space in directory
      command: "du -hs {{ target_dir }}"
      register: space

    - set_fact:
        free_space_bytes: "{{ (space.stdout_lines[1] | split)[3] }}"