---

- name: Test task
  gather_facts: false
  hosts: all
  vars:
    path: /mnt/user/appdata/qbittorrent/VueTorrent/

  tasks:
  - name: Task name
    stat:
      path: '{{ path }}'
    register: register_name
  
  - name: Task name 2
    file:
      path: '{{ path }}'
      state: touch
    when: not register_name.stat.exists
...