---

- name: Test task
  gather_facts: false
  hosts: all
  vars:
    target_dir: "/mnt/user/downloads/tv"

  tasks:
    # FACTS ##################################################################                                                                                                             #####
    - name: Check sufficient free space in directory
      command: "du -hs {{ target_dir }}"
      register: space

    - name: Print return information from the previous task
      ansible.builtin.debug:
        msg: "{{ space.stdout }}"

    - name: Send notify to Telegram
      community.general.telegram:
        token: '5270927352:AAHHbj1KefSx7XYffQke_NQGRxoo_L9q7YQ'
        api_args:
          chat_id: 5270927352
          parse_mode: "markdown"
          text: "Your precious application has been deployed: https://example.com"
          disable_web_page_preview: true
          disable_notification: false