---

- name: Update VueTorrent
  gather_facts: false
  hosts: all
  vars:
    path: /mnt/user/appdata/qbittorrent/VueTorrent/

  tasks:
  - name: Clone a github repository
    git:
      repo: https://github.com/WDaan/VueTorrent.git
      dest: '{{ path }}'
      clone: yes
      update: yes
... 
