---

- name: Update Sonarr Extended Scripts
  gather_facts: false
  hosts: all

  tasks:
    # FACTS ##################################################################
    - name: Download Sonarr extended.conf
      ansible.builtin.get_url:
        url: https://github.com/RandomNinjaAtk/arr-scripts/blob/main/sonarr/extended.conf
        dest: /mnt/user/appdata/sonarr/

    - name: Restart a container
      community.docker.docker_container:
        name: sonarr
        state: started
        restart: true
    
    - name: Waits for connections, don't start checking for 30 seconds
      ansible.builtin.wait_for:
        host: 192.168.2.16
        delay: 30
        port: 8989

    - name: Restart a container
      community.docker.docker_container:
        name: sonarr
        state: started
        restart: true