---

- name: Update Sonarr Extended Scripts
  gather_facts: false
  hosts: all

  tasks:
    # FACTS ##################################################################
    - name: Stop a container
      community.docker.docker_container:
        name: sonarr
        state: stopped
        
    - name: Update Sonarr Extended Scripts
      shell: |
        wget https://raw.githubusercontent.com/RandomNinjaAtk/arr-scripts/main/sonarr/extended.conf >> /mnt/user/appdata/sonarr/extended.conf
    
    - name: Ensure SELinux is set to enforcing mode
      ansible.builtin.lineinfile:
        path: /mnt/user/appdata/sonarr/extended.conf
        regexp: '^plexUrl=""'
        line: plexUrl="http://192.168.2.16:32400"
    
    - name: Ensure SELinux is set to enforcing mode
      ansible.builtin.lineinfile:
        path: /mnt/user/appdata/sonarr/extended.conf
        regexp: '^plexToken=""'
        line: plexToken="yyUBMrLWTPW2FWhchH1h"
        
    - name: Restart a container
      community.docker.docker_container:
        name: sonarr
        state: started
        
    - name: Waits for connections, don't start checking for 30 seconds
      ansible.builtin.wait_for:
        host: 192.168.2.16
        delay: 30
        port: 8989

    - name: Restart a container
      community.docker.docker_container:
        name: sonarr
        state: started
        restart: true
        
    - name: Waits for connections, don't start checking for 30 seconds
      ansible.builtin.wait_for:
        host: 192.168.2.16
        delay: 30
        port: 8989

    - name: Restart a container
      community.docker.docker_container:
        name: sonarr
        state: started
        restart: true
