---

- name: Docker Prune
  gather_facts: false
  hosts: unraid

  tasks:
  - name: Prune everything
    community.docker.docker_prune:
      containers: true
      images: true
      networks: true
      volumes: true
      builder_cache: true