---

- name: Test task
  gather_facts: false
  hosts: unraid

  tasks:
  - name: Install requirements
    shell: |
      pip3 install plexapi
      pip3 install pexpect

  - name: Clone a github repository
    git:
      repo: https://github.com/YoonAddicting/PlexSmartPlaylistDeduplicator.git
      dest: '/mnt/user/appdata/plex/PlexSmartPlaylistDeduplicator'
      clone: yes
      update: yes

  - name: Run script to remove duplicates
    expect:
      command: python3 /mnt/user/appdata/plex/PlexSmartPlaylistDeduplicator/main.py
      responses:
        'Enter your username for Plex' : ''
        'Password' : ''
        'Enter the server identifier' : ''
        'Enter the name of the playlist to remove duplicates from' : ''
        
... 
