---

- name: Test task
  gather_facts: false
  become: true
  hosts: unraid
  vars:
    chat_token: 5270927352:AAHHbj1KefSx7XYffQke_NQGRxoo_L9q7YQ

  tasks:
  - name: Disk Usage
    shell: |
      du -h --max-depth=2 /mnt/nvme_cache/ | sort -g | awk '{ 
        numBytes = $1 * 1024; 
        numUnits = split("B K M G T P", unit); 
        num = numBytes; 
        iUnit = 0; 
        while(num >= 1024 && iUnit + 1 < numUnits) { 
            num = num / 1024; 
            iUnit++; 
        } 
        $1 = sprintf( ((num == 0) ? "%6d%s " : "%6.1f%s "), num, unit[iUnit + 1]);
        print $0; 
        }'
    register: space

  - name: Send notify to Telegram
    community.general.telegram:
      token: "{{ chat_token }}"
      api_args:
        chat_id: 5073078093
        parse_mode: html
        text: "{{ space.stdout }}"
        disable_web_page_preview: true
        disable_notification: false

  - name: Rsync
    shell: |
      rsync -av /mnt/disks/movies/* /mnt/user/movies/
      rm -R /mnt/disks/movies

  - name: Disk Usage
    shell: |
      du -h --max-depth=2 /mnt/nvme_cache/ | sort -g | awk '{ 
        numBytes = $1 * 1024; 
        numUnits = split("B K M G T P", unit); 
        num = numBytes; 
        iUnit = 0; 
        while(num >= 1024 && iUnit + 1 < numUnits) { 
            num = num / 1024; 
            iUnit++; 
        } 
        $1 = sprintf( ((num == 0) ? "%6d%s " : "%6.1f%s "), num, unit[iUnit + 1]);
        print $0; 
        }'
    register: space

  - name: Send notify to Telegram
    community.general.telegram:
      token: "{{ chat_token }}"
      api_args:
        chat_id: 5073078093
        parse_mode: html
        text: "{{ space.stdout }}"
        disable_web_page_preview: true
        disable_notification: false
... 